### ISSUE TITLE
Decide about Slack or Facebook

### ISSUE THREAD

**Issue by bensventures** [Daysk/daysk-bot#1]
Facebook is a nice way to start but maybe our user, which are at the core professionals, would/should not be hanging around there. Would Slack be a better option maybe? How hard is it to build a bot for it compared to Facebook. 

Or should we go multiplatform from the start? Using some frameworks maybe? Botkit?

Let's discuss.

**Comment by EderikAlexander** [comment]
Hi @bensventures, 

I think you can tell us better where your clients are. For us Facebook is the place we are used to. But i just found some interesting stuff about slack and zaphier: https://zapier.com/blog/how-to-build-chat-bot/ so that is also possible. I will have a look at multiplatform bots. That might be a super interesting way to start. 

But the question remains, where are your clients mostly?

**Comment by bensventures** [comment]
I don't think the bulk of our clients are using Facebook during office time. Or at least they shoudn't :trollface: So yeah, it would probably be more interesting for us to have the bot on Slack, and Facebook as a nice-to-have. 

have you checked https://www.lita.io/ or https://github.com/davidmann4/botstack ?

**Comment by sbuffose** [comment]
I've read the documentation about Slack (https://api.slack.com/bot-users). Here are some pros and cons, and details vs. FB messenger's platform.

**Details:**
- Slack has two different kinds of bot users: custom bots and app bots.
- **Custom bot** users are useful for when you want to build something custom for your own team and have no interest in distributing it to other teams.
- **App bot** require you to attach it to a Slack app.
- Slack uses a WebSocket while FB Messenger uses a WebHook

**Pros:**
- Can send a message to a **private group** or **direct message channel** in the same way, but using a Group ID or DM channel ID. _(I have to make some research to understand if this is possible in FB Messenger)_

**Cons:**
- The RTM API only supports posting simple messages.
- For more complex messages we need to use: chat.postMessage Web API method with as_user set to true (https://api.slack.com/methods/rtm.connect), **but I couldn't find documentation at all** on how to send a different type of messages (carrousel, list items, photos, etc.). Is it possible?

**Botkit is amazing!**, BUT all the documentation I could find about it is written in Javascript (https://github.com/howdyai/botkit/blob/master/docs/readme-slack.md). Even if we would like to use it for FB Messenger, all is in Javascript.


**Conclusions:**
1. _Unless we are looking for simple "string" messages responses, I wouldn't recommend using a Custom-bot from Slack._ 
2. _If we cannot find the documentation of Botkit for RoR, I would prefer working with the FB Messenger platform._

**Anyway, I am open to whatever the team is more comfortable! =)**

**Comment by sbuffose** [comment]
@bensventures, I found Lita interesting but still cannot find documentation in the same way there is for FB Messenger (https://developers.facebook.com/docs/messenger-platform/product-overview/conversation).

I found even more interesting BotStack. All the easy methods are already built, and using the same script we used for our app:

`
Bot.on :message do |message|
--
  | BotLogic::handle_request(message, "TEXT")
  | end
  |  
  | Bot.on :postback do |postback|
  | BotLogic::handle_request(postback, "CALLBACK")
  | end
  |  
  | Bot.on :optin do |optin|
  | BotLogic::handle_request(optin, "OPTIN")
  | end
  |  
  | Bot.on :delivery do |delivery|
  | #BotLogic::handle_request(delivery, "DELIVERY")
  | end
`

**My only worry now is if we need carrousel, list and paying inside the chatbot; I couldn't find a way to send them on Slack.**

**Comment by bensventures** [comment]
Ok guys, I hear you. I think Facebook is the way to go. And if you are comfortable with BotStack then I think it is worth using it to streamline all the dirty work.

**Comment by EderikAlexander** [comment]
I also think that is the best way to start. I think it doesn't harm to have a FB bot aswell... After that we can still do the slack bot.. I would love to try that out aswell.
