### ISSUE TITLE
Prepare all necessary keys and account setup

### ISSUE THREAD

**Issue by bensventures** [Daysk/daysk-bot#2]
Before starting coding away we could setup the different accounts and generate keys and such. At least the ones we already know we're going to need.

**Comment by bensventures** [comment]
I've created a Facebook App for the bot. If you give me your Facebook names I can add you as Admin so you can generate the keys etc...

**Comment by EderikAlexander** [comment]
@bensventures my name is Ederik van Koldenhoven :)

**Comment by EderikAlexander** [comment]
@bensventures, can you add me..?

**Comment by sbuffose** [comment]
@bensventures Sebastian Buffo Sempe

**Comment by libsyz** [comment]
faisa klinsmann

**Comment by sbuffose** [comment]
@bensventures, we don't know if it can be a problem but we are using this rails version: 5.0.3 , and this ruby version: 2.3.3p222.

**Comment by sbuffose** [comment]
We are started building the ChatBot from the coding perspective, but we also need to follow this steps:

- Create an App and a Page (DONE)
- Setup a Webhook
- Get a Page Access Token
- Subscribe the App to a Page
- Test your bot

Once we have access, we can do steps 2 to 5 by ourselves.

**Comment by sbuffose** [comment]
Also, we need to remember to subscribe the Web Page to FB by using:
`curl -X POST "https://graph.facebook.com/v2.9/me/subscribed_apps?access_token=PAGE_ACCESS_TOKEN"`

**Comment by bensventures** [comment]
I've just got the control of the account back and added you to the Facebook app Daysk bot staging. Please confirm you have access. Thx!

**Comment by sbuffose** [comment]
Confirmed! I have access.

**Comment by EderikAlexander** [comment]
I have access

**Comment by bensventures** [comment]
Closing this, I think we're done
