### ISSUE TITLE
Say Hi!

### ISSUE THREAD

**Issue by bensventures** [Daysk/daysk-bot#3]
As a first step I want to be able to talk to the bot, saying "Hi" or "Hello" and get a reply back. Saying one of those two words should restart the conversasion.

This task involves creating the first core of the bot and setting it up on a server. The bot should have all the keys and permissions to chat with the selected app (Facebook or Slack)

**Comment by EderikAlexander** [comment]
@bensventures i think this one can be closed right? Because it is in the other issues aswell... 

Agree?

**Comment by bensventures** [comment]
If you are referring to #4 then it is not exactly the same. This story is for the base line, from where we will build #4. I think we need to do both in order. Step by step if you will.

**Comment by libsyz** [comment]
@bensventures  The bot is able to greet! Ederik will prepare a short video to show you  :)

**Comment by sbuffose** [comment]
@bensventures Would you like to use the GET STARTED button? We can actually add a slogan (in our case, for Bellboy, it was: "Take your hotel concierge in your pocket". -> You can see it in the image attached). Once you press in the GET STARTED, you get the greeting (second image).

![img_0864](https://user-images.githubusercontent.com/18401014/28319817-57c7a208-6ba5-11e7-928e-aa7d1161fae9.PNG)

![img_0865](https://user-images.githubusercontent.com/18401014/28320037-e9900b58-6ba5-11e7-9c15-b256711e070e.PNG)

**Comment by bensventures** [comment]
Yes a slogan would be great, let's use "Offices and meeting rooms on demand, just ask"

**Comment by sbuffose** [comment]
Great! So we will include the GET STARTED button and place that slogan. Shall we provide with some quick replies or only greet the user.

**Comment by bensventures** [comment]
For now just greet the user.

**Comment by sbuffose** [comment]
Greeting with slogan and GET STARTED button running in DayskTest Page.
![img_0872](https://user-images.githubusercontent.com/18401014/28421951-05d623c2-6d3d-11e7-8098-5debe66619ac.PNG)

**Comment by bensventures** [comment]
Great job guys, closing.

**Comment by bensventures** [comment]
Remember to put the issue id in the pull request so it gets closed automatically when we merge.
